crypto_patterns:
  DH:
    description: Diffie-Hellman key exchange - not quantum resistant
    patterns:
    - DH_new\s*\(
    - DH_free\s*\(
    - SSL_CTX_set_tmp_dh\s*\(
    - DH\s*\*\s*\w+
    - DH_generate_\w+\s*\(
    - ssl_callback_TmpDH\b
    recommendation: Replace with ML-KEM (NIST Kyber) for key exchange
    severity: HIGH
  DSA:
    description: DSA algorithm usage - not quantum resistant
    patterns:
    - EVP_PKEY_DSA\b
    - DSA_\w+\s*\(
    - DSA\s*\*\s*\w+
    - PEM_read.*DSA\w*\s*\(
    recommendation: Replace with ML-DSA (NIST Dilithium) for signatures
    severity: HIGH
  ECDSA_EC:
    description: ECDSA/EC algorithm usage - not quantum resistant
    patterns:
    - EVP_PKEY_EC\b
    - EC_KEY_\w+\s*\(
    - ECDH_\w+\s*\(
    - SSL_CTX_set_tmp_ecdh\s*\(
    - EC_KEY\s*\*\s*\w+
    - NID_X9_62_prime256v1\b
    - NID_secp\w+\b
    recommendation: Replace ECDSA with ML-DSA, ECDH with ML-KEM (Kyber)
    severity: HIGH
  Legacy_TLS:
    description: Legacy SSL/TLS protocol versions
    patterns:
    - SSLv2_\w+_method\s*\(
    - SSLv3_\w+_method\s*\(
    - TLSv1_\w+_method\s*\(
    - TLSv1_1_\w+_method\s*\(
    - TLSv1_2_\w+_method\s*\(
    - SSL_PROTOCOL_SSLV[23]\b
    - SSL_PROTOCOL_TLSV1[^_3]\b
    recommendation: Upgrade to TLS 1.3 with post-quantum cipher suites
    severity: MEDIUM
  RSA:
    description: RSA algorithm usage - not quantum resistant
    patterns:
    - SSL_CTX_use_RSAPrivateKey\s*\(
    - EVP_PKEY_RSA\b
    - RSA_\w+\s*\(
    - PEM_read.*RSA\w*\s*\(
    - RSA\s*\*\s*\w+
    - RSA_new\s*\(
    - RSA_free\s*\(
    recommendation: Replace with ML-DSA (NIST Dilithium) for signatures
    severity: HIGH
  Weak_Cipher:
    description: Weak cipher or hash algorithm
    patterns:
    - RC4\b
    - DES\b(?!C)
    - 3DES\b
    - MD5\b
    - SHA1\b(?!6|28|384|512)
    recommendation: Use AES-256 and SHA-256/SHA-3 minimum
    severity: MEDIUM
  Weak_Key_Size:
    description: "Weak key size detected (\u22641024 bits)"
    patterns:
    - (?:keylen|key_size|bits?)\s*[=<]\s*(?:512|1024)\b
    - (?:512|1024).*(?:bit|key)
    - get_rfc2409_prime_1024\b
    recommendation: Use minimum 2048-bit keys, preferably 3072+
    severity: MEDIUM
exclude_dirs:
- test
- tests
- examples
- docs
- .git
exclude_files:
- '*_test.cpp'
- '*_example.cpp'
file_types:
- .cpp
- .h
- .hpp
- .cc
- .cxx
- .c
